# Generated by Django 4.0.5 on 2022-07-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
