# Generated by Django 4.0.5 on 2022-07-17 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_token_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
